// Football clubs with logo URLs from api-sports CDN
export interface FootballClub {
  name: string;
  region: 'ARG' | 'BRA' | 'LATAM' | 'ESP' | 'ENG' | 'DEU' | 'ITA' | 'FRA' | 'EUR' | 'ASIA';
  logo: string;
}

export const CLUB_REGIONS: Record<FootballClub['region'], string> = {
  ARG:  'Argentina',
  BRA:  'Brasil',
  LATAM:'LATAM',
  ESP:  'España',
  ENG:  'Inglaterra',
  DEU:  'Alemania',
  ITA:  'Italia',
  FRA:  'Francia',
  EUR:  'Europa',
  ASIA: 'Asia',
};

const cdn = (id: number) => `https://media.api-sports.io/football/teams/${id}.png`;

export const FOOTBALL_CLUBS: FootballClub[] = [
  // ─── Argentina ───────────────────────────────────────────────
  { name: 'Boca Juniors',      region: 'ARG',  logo: cdn(405)  },
  { name: 'River Plate',       region: 'ARG',  logo: cdn(403)  },
  { name: 'Racing Club',       region: 'ARG',  logo: cdn(435)  },
  { name: 'Independiente',     region: 'ARG',  logo: cdn(434)  },
  { name: 'San Lorenzo',       region: 'ARG',  logo: cdn(437)  },
  { name: 'Huracán',           region: 'ARG',  logo: cdn(436)  },
  { name: 'Vélez',             region: 'ARG',  logo: cdn(442)  },
  { name: 'Estudiantes',       region: 'ARG',  logo: cdn(430)  },
  { name: 'Lanús',             region: 'ARG',  logo: cdn(438)  },
  { name: 'Argentinos Jrs.',   region: 'ARG',  logo: cdn(428)  },
  { name: 'Talleres',          region: 'ARG',  logo: cdn(441)  },
  { name: 'Belgrano',          region: 'ARG',  logo: cdn(429)  },
  { name: 'Rosario Central',   region: 'ARG',  logo: cdn(440)  },
  { name: "Newell's",          region: 'ARG',  logo: cdn(439)  },
  { name: 'Defensa y J.',      region: 'ARG',  logo: cdn(3424) },
  { name: 'Banfield',          region: 'ARG',  logo: cdn(444)  },
  { name: 'Gimnasia LP',       region: 'ARG',  logo: cdn(432)  },
  { name: 'Atl. Tucumán',      region: 'ARG',  logo: cdn(447)  },
  { name: 'Platense',          region: 'ARG',  logo: cdn(16284)},
  { name: 'Colón',             region: 'ARG',  logo: cdn(433)  },
  { name: 'Unión (SF)',        region: 'ARG',  logo: cdn(3433) },
  // ─── Brasil ──────────────────────────────────────────────────
  { name: 'Flamengo',          region: 'BRA',  logo: cdn(119)  },
  { name: 'Corinthians',       region: 'BRA',  logo: cdn(131)  },
  { name: 'Palmeiras',         region: 'BRA',  logo: cdn(121)  },
  { name: 'São Paulo',         region: 'BRA',  logo: cdn(126)  },
  { name: 'Santos',            region: 'BRA',  logo: cdn(127)  },
  { name: 'Grêmio',            region: 'BRA',  logo: cdn(120)  },
  { name: 'Internacional',     region: 'BRA',  logo: cdn(125)  },
  { name: 'Atlético Mineiro',  region: 'BRA',  logo: cdn(130)  },
  { name: 'Cruzeiro',          region: 'BRA',  logo: cdn(129)  },
  { name: 'Fluminense',        region: 'BRA',  logo: cdn(118)  },
  { name: 'Botafogo',          region: 'BRA',  logo: cdn(117)  },
  { name: 'Vasco',             region: 'BRA',  logo: cdn(1062) },
  { name: 'Sport Recife',      region: 'BRA',  logo: cdn(128)  },
  { name: 'Bahia',             region: 'BRA',  logo: cdn(116)  },
  // ─── LATAM ───────────────────────────────────────────────────
  { name: 'Colo-Colo',         region: 'LATAM',logo: cdn(702)  },
  { name: 'U. de Chile',       region: 'LATAM',logo: cdn(700)  },
  { name: 'U. Católica',       region: 'LATAM',logo: cdn(703)  },
  { name: 'Peñarol',           region: 'LATAM',logo: cdn(880)  },
  { name: 'Nacional (URU)',    region: 'LATAM',logo: cdn(879)  },
  { name: 'Atl. Nacional',     region: 'LATAM',logo: cdn(1068) },
  { name: 'Millonarios',       region: 'LATAM',logo: cdn(1071) },
  { name: 'América de Cali',   region: 'LATAM',logo: cdn(1064) },
  { name: 'Junior',            region: 'LATAM',logo: cdn(1070) },
  { name: 'Alianza Lima',      region: 'LATAM',logo: cdn(1051) },
  { name: 'Universitario',     region: 'LATAM',logo: cdn(1052) },
  { name: 'Olimpia (PY)',      region: 'LATAM',logo: cdn(1085) },
  { name: 'Club América',      region: 'LATAM',logo: cdn(1604) },
  { name: 'Chivas',            region: 'LATAM',logo: cdn(1600) },
  { name: 'Cruz Azul',         region: 'LATAM',logo: cdn(1602) },
  { name: 'Tigres UANL',       region: 'LATAM',logo: cdn(1606) },
  { name: 'Monterrey',         region: 'LATAM',logo: cdn(1605) },
  { name: 'Pumas UNAM',        region: 'LATAM',logo: cdn(1603) },
  { name: 'Atlas',             region: 'LATAM',logo: cdn(1601) },
  // ─── España ──────────────────────────────────────────────────
  { name: 'Real Madrid',       region: 'ESP',  logo: cdn(541)  },
  { name: 'Barcelona',         region: 'ESP',  logo: cdn(529)  },
  { name: 'Atlético Madrid',   region: 'ESP',  logo: cdn(530)  },
  { name: 'Sevilla',           region: 'ESP',  logo: cdn(536)  },
  { name: 'Valencia',          region: 'ESP',  logo: cdn(532)  },
  { name: 'Athletic Bilbao',   region: 'ESP',  logo: cdn(531)  },
  { name: 'Villarreal',        region: 'ESP',  logo: cdn(533)  },
  { name: 'Real Sociedad',     region: 'ESP',  logo: cdn(543)  },
  // ─── Inglaterra ──────────────────────────────────────────────
  { name: 'Manchester City',   region: 'ENG',  logo: cdn(50)   },
  { name: 'Manchester Utd',    region: 'ENG',  logo: cdn(33)   },
  { name: 'Liverpool',         region: 'ENG',  logo: cdn(40)   },
  { name: 'Arsenal',           region: 'ENG',  logo: cdn(42)   },
  { name: 'Chelsea',           region: 'ENG',  logo: cdn(49)   },
  { name: 'Tottenham',         region: 'ENG',  logo: cdn(47)   },
  { name: 'Aston Villa',       region: 'ENG',  logo: cdn(66)   },
  { name: 'Newcastle',         region: 'ENG',  logo: cdn(34)   },
  // ─── Alemania ────────────────────────────────────────────────
  { name: 'Bayern Munich',     region: 'DEU',  logo: cdn(157)  },
  { name: 'Dortmund',          region: 'DEU',  logo: cdn(165)  },
  { name: 'RB Leipzig',        region: 'DEU',  logo: cdn(173)  },
  { name: 'Leverkusen',        region: 'DEU',  logo: cdn(168)  },
  // ─── Italia ──────────────────────────────────────────────────
  { name: 'Juventus',          region: 'ITA',  logo: cdn(496)  },
  { name: 'Inter Milan',       region: 'ITA',  logo: cdn(505)  },
  { name: 'AC Milan',          region: 'ITA',  logo: cdn(489)  },
  { name: 'AS Roma',           region: 'ITA',  logo: cdn(497)  },
  { name: 'Napoli',            region: 'ITA',  logo: cdn(492)  },
  { name: 'Lazio',             region: 'ITA',  logo: cdn(487)  },
  // ─── Francia ─────────────────────────────────────────────────
  { name: 'PSG',               region: 'FRA',  logo: cdn(85)   },
  { name: 'Olympique Lyon',    region: 'FRA',  logo: cdn(80)   },
  { name: 'Marseille',         region: 'FRA',  logo: cdn(81)   },
  { name: 'Monaco',            region: 'FRA',  logo: cdn(91)   },
  // ─── Otros Europa ────────────────────────────────────────────
  { name: 'Porto',             region: 'EUR',  logo: cdn(212)  },
  { name: 'Benfica',           region: 'EUR',  logo: cdn(211)  },
  { name: 'Sporting CP',       region: 'EUR',  logo: cdn(228)  },
  { name: 'Ajax',              region: 'EUR',  logo: cdn(194)  },
  { name: 'PSV',               region: 'EUR',  logo: cdn(197)  },
  { name: 'Feyenoord',         region: 'EUR',  logo: cdn(193)  },
  { name: 'Celtic',            region: 'EUR',  logo: cdn(360)  },
  { name: 'Rangers',           region: 'EUR',  logo: cdn(359)  },
  // ─── Asia / Middle East ──────────────────────────────────────
  { name: 'Al-Nassr',          region: 'ASIA', logo: cdn(2932) },
  { name: 'Al-Hilal',          region: 'ASIA', logo: cdn(2931) },
  { name: 'Urawa Reds',        region: 'ASIA', logo: cdn(304)  },
];
